<?php

use Illuminate\Database\Seeder;

class QuestionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {


        $sorted = [];
        $Questions = array(
            array('QuestionID' => '1','Slug' => 'starkast','Question' => 'Vem Ã¤r starkast?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '2','Slug' => 'blygast','Question' => 'Vem Ã¤r blygast?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '3','Slug' => 'mest-valtranad','Question' => 'Vem Ã¤r mest vÃ¤ltrÃ¤nad?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '4','Slug' => 'brukar-bli-fullast','Question' => 'Vem brukar bli fullast?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '5','Slug' => 'pratar-mest-i-telefon','Question' => 'Vem pratar mest i telefon?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '6','Slug' => 'galnast','Question' => 'Vem Ã¤r galnast?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '7','Slug' => 'finast-nasa','Question' => 'Vem har finast nÃ¤sa?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '8','Slug' => 'storst-sjalvfortroende','Question' => 'Vem har stÃ¶rst sjÃ¤lvfÃ¶rtroende?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '9','Slug' => 'mest-kreativ','Question' => 'Vem Ã¤r mest kreativ?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '10','Slug' => 'snalast','Question' => 'Vem Ã¤r snÃ¥last?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '11','Slug' => 'snyggast-kladd','Question' => 'Vem Ã¤r snyggast klÃ¤dd?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '12','Slug' => 'haft-sex-flest-ganger','Question' => 'Vem har haft sex flest gÃ¥nger?','IsActive' => '1','IsDirty' => '1','DateAdded' => '0'),
            array('QuestionID' => '13','Slug' => 'snyggast-underklader','Question' => 'Vem har snyggast underklÃ¤der?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '14','Slug' => 'snyggast-skor','Question' => 'Vem har snyggast skor?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '15','Slug' => 'finast-fotter','Question' => 'Vem har finast fÃ¶tter?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '16','Slug' => 'bast-i-sangen','Question' => 'Vem Ã¤r bÃ¤st i sÃ¤ngen?','IsActive' => '1','IsDirty' => '1','DateAdded' => '0'),
            array('QuestionID' => '17','Slug' => 'bast-pa-att-ljuga','Question' => 'Vem Ã¤r bÃ¤st pÃ¥ att ljuga?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '18','Slug' => 'mest-palitlig','Question' => 'Vem Ã¤r mest pÃ¥litlig?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '19','Slug' => 'atit-mest-skrapmat','Question' => 'Vem har Ã¤tit mest skrÃ¤pmat?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '20','Slug' => 'mest-generos','Question' => 'Vem Ã¤r mest generÃ¶s?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '21','Slug' => 'bast-ordforrad','Question' => 'Vem har bÃ¤st ordfÃ¶rrÃ¥d?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '22','Slug' => 'anvander-internet-mest','Question' => 'Vem anvÃ¤nder internet mest?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '23','Slug' => 'skickar-flest-sms','Question' => 'Vem skickar flest sms?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '24','Slug' => 'latast','Question' => 'Vem Ã¤r latast?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '25','Slug' => 'ser-mest-pa-tv','Question' => 'Vem ser mest pÃ¥ TV?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '27','Slug' => 'laser-mest-bocker','Question' => 'Vem lÃ¤ser mest bÃ¶cker?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '28','Slug' => 'bast-pa-att-kyssas','Question' => 'Vem Ã¤r bÃ¤st pÃ¥ att kyssas?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '30','Slug' => 'spelar-mest-tv-spel','Question' => 'Vem spelar mest TV-Spel?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '31','Slug' => 'finast-ogon','Question' => 'Vem har finast Ã¶gon?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '32','Slug' => 'modigast','Question' => 'Vem Ã¤r modigast?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '33','Slug' => 'smartast','Question' => 'Vem Ã¤r smartast?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '34','Slug' => 'skrattar-mest','Question' => 'Vem skrattar mest?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '35','Slug' => 'festar-mest','Question' => 'Vem festar mest?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '36','Slug' => 'snyggast','Question' => 'Vem Ã¤r snyggast?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '37','Slug' => 'storst-sjalvfortroende','Question' => 'Vem har stÃ¶rst sjÃ¤lvfÃ¶rtroende?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '38','Slug' => 'shoppar-mest','Question' => 'Vem shoppar mest?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '39','Slug' => 'skvallrar-mest','Question' => 'Vem skvallrar mest?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '40','Slug' => 'sett-flest-filmer','Question' => 'Vem har sett flest filmer?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '41','Slug' => 'sotast','Question' => 'Vem Ã¤r sÃ¶tast?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '42','Slug' => 'kan-bli-argast','Question' => 'Vem kan bli argast?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '43','Slug' => 'mest-pedant','Question' => 'Vem Ã¤r mest pedant?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '44','Slug' => 'finast-hander','Question' => 'Vem har finast hÃ¤nder?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '45','Slug' => 'grater-mest','Question' => 'Vem grÃ¥ter mest?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '46','Slug' => 'sexigast','Question' => 'Vem Ã¤r sexigast?','IsActive' => '1','IsDirty' => '1','DateAdded' => '0'),
            array('QuestionID' => '47','Slug' => 'snallast','Question' => 'Vem Ã¤r snÃ¤llast?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '48','Slug' => 'mest-fafang','Question' => 'Vem Ã¤r mest fÃ¥fÃ¤ng?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '49','Slug' => 'mest-egensinnig','Question' => 'Vem Ã¤r mest egensinnig?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '50','Slug' => 'coolast','Question' => 'Vem Ã¤r coolast?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '51','Slug' => 'spenderar-mest-tid-pa-facebook','Question' => 'Vem spenderar mest tid pÃ¥ facebook?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '52','Slug' => 'galnast','Question' => 'Vem Ã¤r galnast?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '53','Slug' => 'mest-allmanbildad','Question' => 'Vem Ã¤r mest allmÃ¤nbildad?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '96','Slug' => 'bli-gay','Question' => 'Vem kommer bli gay?','IsActive' => '1','IsDirty' => '1','DateAdded' => '0'),
            array('QuestionID' => '56','Slug' => 'Ã–verleva-pa-en-ode-o','Question' => 'Ã–verleva pÃ¥ en Ã¶de Ã¶','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '57','Slug' => 'bli-uteliggare','Question' => 'Vem kommer bli uteliggare?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '58','Slug' => 'bli-rik','Question' => 'Vem kommer bli rik?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '59','Slug' => 'storst-mammagris','Question' => 'Vem Ã¤r stÃ¶rst mammagris?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '60','Slug' => 'storst-risk-att-do-i-hiv','Question' => 'Vem har stÃ¶rst risk att dÃ¶ i hiv?','IsActive' => '1','IsDirty' => '1','DateAdded' => '0'),
            array('QuestionID' => '61','Slug' => 'fa-barn-forst','Question' => 'Vem kommer fÃ¥ barn fÃ¶rst?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '62','Slug' => 'hitta-den-snyggaste-livspartnern','Question' => 'Vem kommer hitta den snyggaste livspartnern?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '63','Slug' => 'fa-den-snyggaste-tjejen/killen','Question' => 'Vem kommer fÃ¥ den snyggaste tjejen/killen?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '64','Slug' => 'blir-mest-tutad-pa','Question' => 'Vem blir mest tutad pÃ¥?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '65','Slug' => 'do-forst','Question' => 'Vem kommer dÃ¶ fÃ¶rst?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '66','Slug' => 'gillar-ett-finger-i-rumpan-mest','Question' => 'Vem gillar ett finger i rumpan mest?','IsActive' => '1','IsDirty' => '1','DateAdded' => '0'),
            array('QuestionID' => '67','Slug' => 'skulle-prutta-nagon-i-ansiktet','Question' => 'Vem skulle prutta nÃ¥gon i ansiktet?','IsActive' => '1','IsDirty' => '1','DateAdded' => '0'),
            array('QuestionID' => '68','Slug' => 'harigast-fitta','Question' => 'Vem har hÃ¥rigast fitta?','IsActive' => '1','IsDirty' => '1','DateAdded' => '0'),
            array('QuestionID' => '69','Slug' => 'harigast-pung','Question' => 'Vem har hÃ¥rigast pung?','IsActive' => '1','IsDirty' => '1','DateAdded' => '0'),
            array('QuestionID' => '71','Slug' => 'visar-musen-mest','Question' => 'Vem visar musen mest?','IsActive' => '1','IsDirty' => '1','DateAdded' => '0'),
            array('QuestionID' => '72','Slug' => 'visar-kuken-mest','Question' => 'Vem visar kuken mest?','IsActive' => '1','IsDirty' => '1','DateAdded' => '0'),
            array('QuestionID' => '73','Slug' => 'storst-chans-att-hooka-med-en-kandis','Question' => 'Vem har stÃ¶rst chans att hooka med en kÃ¤ndis?','IsActive' => '1','IsDirty' => '1','DateAdded' => '0'),
            array('QuestionID' => '74','Slug' => 'att-pierca-sig-i-konet','Question' => 'Vem kommer att pierca sig i kÃ¶net?','IsActive' => '1','IsDirty' => '1','DateAdded' => '0'),
            array('QuestionID' => '75','Slug' => 'ligger-runt-mest','Question' => 'Vem ligger runt mest?','IsActive' => '1','IsDirty' => '1','DateAdded' => '0'),
            array('QuestionID' => '76','Slug' => 'gillar-analsex-mest','Question' => 'Vem gillar analsex mest?','IsActive' => '1','IsDirty' => '1','DateAdded' => '0'),
            array('QuestionID' => '77','Slug' => 'delta-i-en-porrfilm','Question' => 'Vem kommer delta i en porrfilm?','IsActive' => '1','IsDirty' => '1','DateAdded' => '0'),
            array('QuestionID' => '78','Slug' => 'doda-nagon','Question' => 'Vem kommer dÃ¶da nÃ¥gon?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '79','Slug' => 'mest-kriminell','Question' => 'Vem Ã¤r mest kriminell?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '80','Slug' => 'skulle-ta-betalt-for-sex','Question' => 'Vem skulle ta betalt fÃ¶r sex?','IsActive' => '1','IsDirty' => '1','DateAdded' => '0'),
            array('QuestionID' => '81','Slug' => 'bli-jattetjock-om-tio-ar','Question' => 'Vem kommer bli jÃ¤ttetjock om tio Ã¥r?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '82','Slug' => 'bli-snyggast-som-gammal','Question' => 'Vem kommer bli snyggast som gammal?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '83','Slug' => 'ha-sex-n-andra-ser-pa','Question' => 'Vem kommer ha sex nÃ¤r andra ser pÃ¥?','IsActive' => '1','IsDirty' => '1','DateAdded' => '0'),
            array('QuestionID' => '84','Slug' => 'mest-&quot;dirty&quot;-i-sangen','Question' => 'Vem Ã¤r mest &quot;dirty&quot; i sÃ¤ngen?','IsActive' => '1','IsDirty' => '1','DateAdded' => '0'),
            array('QuestionID' => '85','Slug' => 'katast','Question' => 'Vem Ã¤r kÃ¥tast?','IsActive' => '1','IsDirty' => '1','DateAdded' => '0'),
            array('QuestionID' => '86','Slug' => 'mysigast-i-sangen','Question' => 'Vem Ã¤r mysigast i sÃ¤ngen?','IsActive' => '1','IsDirty' => '1','DateAdded' => '0'),
            array('QuestionID' => '87','Slug' => 'gifta-sig-forst','Question' => 'Vem kommer gifta sig fÃ¶rst?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '88','Slug' => 'gifta-sig-rik','Question' => 'Vem kommer gifta sig rik?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '89','Slug' => 'bli-missbrukare','Question' => 'Vem kommer bli missbrukare?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '90','Slug' => 'onanerar-mest','Question' => 'Vem onanerar mest?','IsActive' => '1','IsDirty' => '1','DateAdded' => '0'),
            array('QuestionID' => '91','Slug' => 'fa-fulast-barn','Question' => 'Vem kommer fÃ¥ fulast barn?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '92','Slug' => 'jobbigast-som-full','Question' => 'Vem Ã¤r jobbigast som full?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '93','Slug' => 'jobbigast-nykter','Question' => 'Vem Ã¤r jobbigast nykter?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '94','Slug' => 'bli-langtidsarbetslos-som-vuxen','Question' => 'Vem kommer bli lÃ¥ngtidsarbetslÃ¶s som vuxen?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '95','Slug' => 'rosta-pa-sverigedemokraterna','Question' => 'Vem kommer rÃ¶sta pÃ¥ Sverigedemokraterna?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '97','Slug' => 'snyggast-rov','Question' => 'Vem har snyggast rÃ¶v?','IsActive' => '1','IsDirty' => '0','DateAdded' => '0'),
            array('QuestionID' => '99','Slug' => 'lagger-ackligast-brakskitar','Question' => 'Vem lÃ¤gger Ã¤ckligast brakskitar?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1352153219'),
            array('QuestionID' => '100','Slug' => 'samst-humor','Question' => 'Vem har sÃ¤mst humor?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1352157683'),
            array('QuestionID' => '102','Slug' => 'mest-desperat','Question' => 'Vem Ã¤r mest desperat?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1352184785'),
            array('QuestionID' => '103','Slug' => 'kan-tankas-suga-av-sig-sjalv','Question' => 'Vem kan tÃ¤nkas suga av sig sjÃ¤lv?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1352217957'),
            array('QuestionID' => '104','Slug' => 'storst-kuk','Question' => 'Vem har stÃ¶rst kuk?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1352396325'),
            array('QuestionID' => '105','Slug' => 'ser-aldst-ut','Question' => 'Vem ser Ã¤ldst ut?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1352396416'),
            array('QuestionID' => '106','Slug' => 'gillar-godis-mest','Question' => 'Vem gillar godis mest?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1352396465'),
            array('QuestionID' => '107','Slug' => 'haft-mest-sexpartners','Question' => 'Vem har haft mest sexpartners?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1352396597'),
            array('QuestionID' => '108','Slug' => 'legat-runt-mest-pa-festival','Question' => 'Vem har legat runt mest pÃ¥ festival?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1352396630'),
            array('QuestionID' => '109','Slug' => 'skulle-du-helst-ligga-med','Question' => 'Vem skulle du helst ligga med?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1352396897'),
            array('QuestionID' => '110','Slug' => 'fa-coolast-barn','Question' => 'Vem kommer fÃ¥ coolast barn?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1352558997'),
            array('QuestionID' => '111','Slug' => 'fa-mest-barn','Question' => 'Vem kommer fÃ¥ mest barn?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1352559064'),
            array('QuestionID' => '112','Slug' => 'bli-den-basta-pappan','Question' => 'Vem kommer bli den bÃ¤sta pappan?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1352559077'),
            array('QuestionID' => '113','Slug' => 'bli-den-basta-mamman','Question' => 'Vem kommer bli den bÃ¤sta mamman?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1352559091'),
            array('QuestionID' => '114','Slug' => 'blir-mest-bakfull','Question' => 'Vem blir mest bakfull?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1352567187'),
            array('QuestionID' => '115','Slug' => 'lagar-godast-mat','Question' => 'Vem Ã¤r lagar godast mat?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1352567317'),
            array('QuestionID' => '116','Slug' => 'fa-sotast-barn','Question' => 'Vem kommer fÃ¥ sÃ¶tast barn?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1352567374'),
            array('QuestionID' => '117','Slug' => 'de-finaste-brosten','Question' => 'Vem har de finaste brÃ¶sten?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1352567459'),
            array('QuestionID' => '118','Slug' => 'lagar-godast-mat','Question' => 'Vem lagar godast mat?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1352567574'),
            array('QuestionID' => '119','Slug' => 'tal-mest-alkohol','Question' => 'Vem tÃ¥l mest alkohol?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1352567829'),
            array('QuestionID' => '120','Slug' => 'misshandlar-sin-telefon-mest','Question' => 'Vem misshandlar sin telefon mest?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1352568005'),
            array('QuestionID' => '121','Slug' => 'gladast-i-ol','Question' => 'Vem Ã¤r gladast i Ã¶l?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1352568175'),
            array('QuestionID' => '122','Slug' => 'mest-valdsambenagen','Question' => 'Vem Ã¤r mest vÃ¥ldsambenÃ¤gen?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1352568251'),
            array('QuestionID' => '123','Slug' => 'mest-politisk','Question' => 'Vem Ã¤r mest politisk?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1352568267'),
            array('QuestionID' => '124','Slug' => 'finast-rost','Question' => 'Vem har finast rÃ¶st?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1352568282'),
            array('QuestionID' => '125','Slug' => 'sexigast-rost','Question' => 'Vem har sexigast rÃ¶st?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1352568294'),
            array('QuestionID' => '126','Slug' => 'sjunger-falskast-i-duschen','Question' => 'Vem sjunger falskast i duschen?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1352568340'),
            array('QuestionID' => '127','Slug' => 'charmigast','Question' => 'Vem Ã¤r charmigast?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1352568359'),
            array('QuestionID' => '128','Slug' => 'kor-bil-bast','Question' => 'Vem kÃ¶r bil bÃ¤st?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1352568386'),
            array('QuestionID' => '129','Slug' => 'kor-bil-samst','Question' => 'Vem kÃ¶r bil sÃ¤mst?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1352568401'),
            array('QuestionID' => '130','Slug' => 'bast-musiksmak','Question' => 'Vem har bÃ¤st musiksmak?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1352568424'),
            array('QuestionID' => '131','Slug' => 'samst-musiksmak','Question' => 'Vem har sÃ¤mst musiksmak?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1352568457'),
            array('QuestionID' => '132','Slug' => 'snabbast-i-sangen','Question' => 'Vem Ã¤r snabbast i sÃ¤ngen?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1352568602'),
            array('QuestionID' => '136','Slug' => 'skulle-du-aldrig-vilja-ha-sex-med','Question' => 'Vem skulle du aldrig vilja ha sex med?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1359387140'),
            array('QuestionID' => '135','Slug' => 'luktar-varst','Question' => 'Vem luktar v&auml;rst?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1353101216'),
            array('QuestionID' => '236','Slug' => 'legat-med-flest','Question' => 'Vem har legat med flest','IsActive' => '0','IsDirty' => '0','DateAdded' => '1390924304'),
            array('QuestionID' => '138','Slug' => 'finast-rumpa','Question' => 'Vem har finast rumpa?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1361057905'),
            array('QuestionID' => '139','Slug' => 'lattast-att-fa-i-sang','Question' => 'Vem Ã¤r lÃ¤ttast att fÃ¥ i sÃ¤ng?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1361057919'),
            array('QuestionID' => '140','Slug' => 'kom-forst-,-honan-eller-agget','Question' => 'Vem kom fÃ¶rst , hÃ¶nan eller Ã¤gget ?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1361067879'),
            array('QuestionID' => '141','Slug' => 'mest-horunge-av-alla-pa-festen','Question' => 'Vem Ã¤r mest horunge av alla pÃ¥ festen?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1361539224'),
            array('QuestionID' => '142','Slug' => 'klamydia','Question' => 'Vem har klamydia?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1361539229'),
            array('QuestionID' => '143','Slug' => 'aids','Question' => 'Vem har aids?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1361539235'),
            array('QuestionID' => '144','Slug' => 's-mamma--storst-hora','Question' => 'Vems mamma Ã¤r stÃ¶rst hora?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1361539242'),
            array('QuestionID' => '145','Slug' => 'varfor-vill-fellie-suga-av-glendermans-kuk','Question' => 'VarfÃ¶r vill Fellie suga av Glendermans kuk?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1361539266'),
            array('QuestionID' => '146','Slug' => 'spy-ikvall','Question' => 'Vem kommer spy ikvÃ¤ll?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1361902834'),
            array('QuestionID' => '147','Slug' => 'bli-uppraggad-ikvall','Question' => 'Vem kommer bli uppraggad ikvÃ¤ll?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1361902852'),
            array('QuestionID' => '148','Slug' => 'den-skevaste-uppfattningen-av-sig-sjalv','Question' => 'Vem har den skevaste uppfattningen av sig sjÃ¤lv?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1361902883'),
            array('QuestionID' => '149','Slug' => 'snyggast-naken','Question' => 'Vem Ã¤r snyggast naken?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1361902904'),
            array('QuestionID' => '150','Slug' => 'tjana-mest-pengar','Question' => 'Vem kommer tjÃ¤na mest pengar?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1361902953'),
            array('QuestionID' => '151','Slug' => 'skulle-kunna-ga-utan-trosor/kalsonger-till-en-fest','Question' => 'Vem skulle kunna gÃ¥ utan trosor/kalsonger till en fest?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1361902993'),
            array('QuestionID' => '152','Slug' => 'bast-pa-att-sjunga','Question' => 'Vem Ã¤r bÃ¤st pÃ¥ att sjunga?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1361903024'),
            array('QuestionID' => '153','Slug' => 'bast-pa-att-strippa','Question' => 'Vem Ã¤r bÃ¤st pÃ¥ att strippa?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1361903034'),
            array('QuestionID' => '154','Slug' => 'skriva-en-sexnovell','Question' => 'Vem kommer skriva en sexnovell?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1361903063'),
            array('QuestionID' => '155','Slug' => 'sexigast-underklader','Question' => 'Vem har sexigast underklÃ¤der?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1361903079'),
            array('QuestionID' => '156','Slug' => 'mest-hipster','Question' => 'Vem Ã¤r mest hipster?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1361903136'),
            array('QuestionID' => '157','Slug' => 'dansar-sexigast-pa-krogen','Question' => 'Vem dansar sexigast pÃ¥ krogen?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1361903221'),
            array('QuestionID' => '158','Slug' => 'dricker-mest','Question' => 'Vem dricker mest?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1361903235'),
            array('QuestionID' => '159','Slug' => 'borde-dricka-mer','Question' => 'Vem borde dricka mer?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1361903245'),
            array('QuestionID' => '160','Slug' => 'vill-du-helst-ligga-med','Question' => 'vem vill du helst ligga med?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1361903278'),
            array('QuestionID' => '161','Slug' => 'skulle-troligast-spela-in(och-vara-med-i)-en-porrfilm','Question' => 'Vem skulle troligast spela in(och vara med i) en porrfilm?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1361903327'),
            array('QuestionID' => '162','Slug' => 'skulle-ligga-med-chefen','Question' => 'Vem skulle ligga med chefen?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1361903338'),
            array('QuestionID' => '163','Slug' => 'bast-pa-dirty-talk','Question' => 'Vem Ã¤r bÃ¤st pÃ¥ dirty-talk?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1361903364'),
            array('QuestionID' => '164','Slug' => 'skickar-flest-sex-sms','Question' => 'Vem skickar flest sex-sms?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1361903375'),
            array('QuestionID' => '165','Slug' => 'snyggast-stjt','Question' => 'Vem har snyggast stjÃ¤rt?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1361903392'),
            array('QuestionID' => '166','Slug' => 'skulle-ta-med-sina-barn-pa-strippklubb','Question' => 'Vem skulle ta med sina barn pÃ¥ strippklubb?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1361903441'),
            array('QuestionID' => '167','Slug' => 'bast-i-sangen','Question' => 'Vem Ã¤r bÃ¤st i sÃ¤ngen?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1361903456'),
            array('QuestionID' => '168','Slug' => 'bast-pa-att-skaka-rumpa','Question' => 'Vem Ã¤r bÃ¤st pÃ¥ att skaka rumpa?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1361903473'),
            array('QuestionID' => '169','Slug' => 'mest-kinky','Question' => 'Vem Ã¤r mest kinky?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1361903499'),
            array('QuestionID' => '170','Slug' => 'bast-pa-att-ge-oralsex','Question' => 'Vem Ã¤r bÃ¤st pÃ¥ att ge oralsex?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1361903536'),
            array('QuestionID' => '171','Slug' => 'blir-mest-fyllekat','Question' => 'Vem blir mest fyllekÃ¥t?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1361903568'),
            array('QuestionID' => '172','Slug' => 'skulle-strypa-en-katt-for-nojets-skull
','Question' => 'Vem skulle strypa en katt fÃ¶r nÃ¶jets skull?
','IsActive' => '1','IsDirty' => '0','DateAdded' => '1361903653'),
            array('QuestionID' => '173','Slug' => 'den-storsta-samlingen-av-sexleksaker','Question' => 'Vem har den stÃ¶rsta samlingen av sexleksaker?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1361903673'),
            array('QuestionID' => '174','Slug' => 'skulle-vilja-ha/gillar-att-ha-trekant','Question' => 'Vem skulle vilja ha/gillar att ha trekant?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1361903703'),
            array('QuestionID' => '175','Slug' => 'nyktrast','Question' => 'Vem Ã¤r nyktrast?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1361903736'),
            array('QuestionID' => '176','Slug' => 'ser-bast-ut-i-polisonger','Question' => 'Vem ser bÃ¤st ut i polisonger?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1361903810'),
            array('QuestionID' => '177','Slug' => 'vara-fet-om-tio-ar','Question' => 'Vem kommer vara fet om tio Ã¥r?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1361903837'),
            array('QuestionID' => '179','Slug' => 'sex-oftast','Question' => 'Vem har sex oftast?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1361903953'),
            array('QuestionID' => '180','Slug' => 'ater-mest','Question' => 'Vem Ã¤ter mest?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1361903991'),
            array('QuestionID' => '239','Slug' => 'haft-det-konstigaste-sexet','Question' => 'Vem har haft det konstigaste sexet?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1390924435'),
            array('QuestionID' => '182','Slug' => 'hoppar-pa-gatan-mest','Question' => 'Vem hoppar pÃ¥ gatan mest?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1363462418'),
            array('QuestionID' => '183','Slug' => 'motionerar-mest','Question' => 'Vem motionerar mest?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1363462434'),
            array('QuestionID' => '184','Slug' => 'pruttar-mest','Question' => 'Vem pruttar mest?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1363462442'),
            array('QuestionID' => '185','Slug' => 'finast-tander','Question' => 'Vem har finast tÃ¤nder?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1363462452'),
            array('QuestionID' => '186','Slug' => 'snuskigast','Question' => 'Vem Ã¤r snuskigast','IsActive' => '1','IsDirty' => '1','DateAdded' => '1363462458'),
            array('QuestionID' => '187','Slug' => 'mest-unibrow','Question' => 'Vem har mest unibrow ?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1363462468'),
            array('QuestionID' => '188','Slug' => 'storst-nasa','Question' => 'Vem har stÃ¶rst nÃ¤sa?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1363462476'),
            array('QuestionID' => '189','Slug' => 'tycker-jag--snyggast','Question' => 'Vem tycker jag Ã¤r snyggast?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1363462487'),
            array('QuestionID' => '190','Slug' => 'uppskattar-sin-partner-mest','Question' => 'Vem uppskattar sin partner mest?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1363462499'),
            array('QuestionID' => '191','Slug' => 'bast-i-skolan','Question' => 'Vem Ã¤r bÃ¤st i skolan?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1363462509'),
            array('QuestionID' => '192','Slug' => 'lyssnar-pa-mest-hard-rock','Question' => 'Vem lyssnar pÃ¥ mest hÃ¥rd rock?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1363462516'),
            array('QuestionID' => '193','Slug' => 'lyssnar-mest-pa-jazz','Question' => 'Vem lyssnar mest pÃ¥ jazz?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1363462524'),
            array('QuestionID' => '194','Slug' => 'lagger-mest-tid-pa-skolan','Question' => 'Vem lÃ¤gger mest tid pÃ¥ skolan?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1363462537'),
            array('QuestionID' => '195','Slug' => 'hemma-mest','Question' => 'Vem Ã¤r hemma mest?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1363462542'),
            array('QuestionID' => '196','Slug' => 'brakar-mest-med-larna','Question' => 'Vem brÃ¥kar mest med lÃ¤rarna?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1363462551'),
            array('QuestionID' => '240','Slug' => 'skulle-kunna-tanka-sig-att-vara-med-nagon-i-detta-rum','Question' => 'Vem skulle kunna tÃ¤nka sig att vara med nÃ¥gon i detta rum?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1390924456'),
            array('QuestionID' => '198','Slug' => 'mest-kat-ikvall','Question' => 'Vem Ã¤r mest kÃ¥t ikvÃ¤ll?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1368047194'),
            array('QuestionID' => '199','Slug' => 'roker-mest-cannabis','Question' => 'vem rÃ¶ker mest cannabis?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1368830542'),
            array('QuestionID' => '201','Slug' => 'katast','Question' => 'Vem Ã¤r kÃ¥tast?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1372532368'),
            array('QuestionID' => '202','Slug' => 'tjockast','Question' => 'Vem Ã¤r tjockast?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1374007897'),
            array('QuestionID' => '203','Slug' => 'bajsar-mest','Question' => 'Vem bajsar mest ','IsActive' => '1','IsDirty' => '0','DateAdded' => '1374981169'),
            array('QuestionID' => '204','Slug' => 'spelar-bast','Question' => 'Vem spelar bÃ¤st','IsActive' => '1','IsDirty' => '0','DateAdded' => '1374981197'),
            array('QuestionID' => '241','Slug' => 'skulle-kunna-tanka-sig-att-ligga-med-en-tjej','Question' => 'Vem skulle kunna tÃ¤nka sig att ligga med en tjej?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1390924472'),
            array('QuestionID' => '208','Slug' => 'mest-gay','Question' => 'Vem Ã¤r mest gay?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1377901575'),
            array('QuestionID' => '209','Slug' => 'ater-mest-bajs','Question' => 'Vem Ã¤ter mest bajs?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1378587810'),
            array('QuestionID' => '210','Slug' => 'svarar-pa-ett-telefonsamtal-under-samlag','Question' => 'Vem svarar pÃ¥ ett telefonsamtal under samlag?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1381090527'),
            array('QuestionID' => '211','Slug' => 'sager-fel-namn-under-samlag','Question' => 'Vem sÃ¤ger fel namn under samlag?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1381090546'),
            array('QuestionID' => '212','Slug' => 'fan--bast','Question' => 'Vem fan Ã¤r bÃ¤st?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1381090558'),
            array('QuestionID' => '214','Slug' => 'diskar-bast','Question' => 'Vem diskar bÃ¤st?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1382118445'),
            array('QuestionID' => '216','Slug' => 'samst-i-sangen','Question' => 'Vem Ã¤r sÃ¤mst i sÃ¤ngen?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1384636226'),
            array('QuestionID' => '217','Slug' => 'fulast-frisyr','Question' => 'Vem har fulast frisyr?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1384636241'),
            array('QuestionID' => '218','Slug' => 'samst-pa-engelska','Question' => 'Vem Ã¤r sÃ¤mst pÃ¥ engelska?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1384636251'),
            array('QuestionID' => '219','Slug' => 'mest-pinsam','Question' => 'Vem Ã¤r mest pinsam?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1384636262'),
            array('QuestionID' => '220','Slug' => 'kissar-mest-pa-fyllan','Question' => 'Vem kissar mest pÃ¥ fyllan?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1384636274'),
            array('QuestionID' => '221','Slug' => 'fulast-tatuering','Question' => 'Vem har fulast tatuering?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1384636341'),
            array('QuestionID' => '222','Slug' => 'samst-pa-att-skamta','Question' => 'Vem Ã¤r sÃ¤mst pÃ¥ att skÃ¤mta?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1384636367'),
            array('QuestionID' => '223','Slug' => 'fulast-trosor','Question' => 'Vem har fulast trosor?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1384636400'),
            array('QuestionID' => '224','Slug' => 'tontigast','Question' => 'Vem Ã¤r tÃ¶ntigast?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1384636419'),
            array('QuestionID' => '244','Slug' => 'fulast','Question' => 'Vem Ã¤r fulast?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1397334378'),
            array('QuestionID' => '243','Slug' => 'sexigast','Question' => 'Vem Ã¤r sexigast?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1397334356'),
            array('QuestionID' => '227','Slug' => 'dricker-dyrast-alkohol','Question' => 'Vem dricker dyrast alkohol?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1388523428'),
            array('QuestionID' => '228','Slug' => 'dricker-mest-fulsprit','Question' => 'Vem dricker mest fulsprit?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1388525458'),
            array('QuestionID' => '229','Slug' => 'var-inte-planerad','Question' => 'Vem var inte planerad?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1388538530'),
            array('QuestionID' => '242','Slug' => 'mest-k','Question' => 'vem Ã¤r mest kÃ¤r ','IsActive' => '0','IsDirty' => '0','DateAdded' => '1394316527'),
            array('QuestionID' => '237','Slug' => 'hade-analsex-senast','Question' => 'Vem hade analsex senast?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1390924342'),
            array('QuestionID' => '238','Slug' => 'gillar-att-bli-slickad-i-rumpan','Question' => 'Vem gillar att bli slickad i rumpan?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1390924381'),
            array('QuestionID' => '245','Slug' => 'sotast-klaning-
v','Question' => 'Vem Ã¤r sÃ¶tast klÃ¤ning 
V','IsActive' => '0','IsDirty' => '0','DateAdded' => '1398743749'),
            array('QuestionID' => '246','Slug' => 'finast-klader
--sotast
-far-nya-klader','Question' => 'Vem har finast klÃ¤der
Vem Ã¤r sÃ¶tast
Vem fÃ¥r Nya klÃ¤der','IsActive' => '0','IsDirty' => '0','DateAdded' => '1398743967'),
            array('QuestionID' => '247','Slug' => 'mest-sannolikt-bli-en-katt-tant','Question' => 'Vem Ã¤r mest sannolikt bli en katt tant?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1398832108'),
            array('QuestionID' => '248','Slug' => 'ligger-runt-mest','Question' => 'Vem ligger runt mest?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1398832126'),
            array('QuestionID' => '249','Slug' => 'n55if1--&lt;a-href=&quot;http://tfzfvxqggorv.com/&quot;&gt;tfzfvxqggorv&lt;/a&gt;,-[url=http://ugkghtkxwcvx.com/]ugkghtkxwcvx[/url],-[link=http://itvhvnfxpeby.com/]itvhvnfxpeby[/link],-http://pirswzmfzymi.com/','Question' => 'n55if1  &lt;a href=&quot;http://tfzfvxqggorv.com/&quot;&gt;tfzfvxqggorv&lt;/a&gt;, [url=http://ugkghtkxwcvx.com/]ugkghtkxwcvx[/url], [link=http://itvhvnfxpeby.com/]itvhvnfxpeby[/link], http://pirswzmfzymi.com/','IsActive' => '0','IsDirty' => '0','DateAdded' => '1399126098'),
            array('QuestionID' => '250','Slug' => 'kissar-i-duschen','Question' => 'Vem kissar i duschen?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1401101089'),
            array('QuestionID' => '251','Slug' => 'skulle-du-inte-vilja-lana-ut-din-bil-till','Question' => 'Vem skulle du inte vilja lÃ¥na ut din bil till?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1401101142'),
            array('QuestionID' => '252','Slug' => 'snyggast-mamma','Question' => 'Vem har snyggast mamma?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1401101158'),
            array('QuestionID' => '253','Slug' => 'grater-till-filmer','Question' => 'Vem grÃ¥ter till filmer?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1401101178'),
            array('QuestionID' => '254','Slug' => 'klumpigast','Question' => 'Vem Ã¤r klumpigast? ','IsActive' => '1','IsDirty' => '0','DateAdded' => '1401101189'),
            array('QuestionID' => '255','Slug' => 'svarar-aldrig-i-telefon','Question' => 'Vem svarar aldrig i telefon? ','IsActive' => '1','IsDirty' => '0','DateAdded' => '1401101208'),
            array('QuestionID' => '256','Slug' => 'fucking-king','Question' => 'Vem Ã¤r fucking king? ','IsActive' => '0','IsDirty' => '0','DateAdded' => '1401101243'),
            array('QuestionID' => '257','Slug' => 'skulle-stalla-upp-i-paradise-hotel','Question' => 'Vem skulle stÃ¤lla upp i paradise hotel? ','IsActive' => '1','IsDirty' => '0','DateAdded' => '1401101259'),
            array('QuestionID' => '258','Slug' => 'dyrast-klader','Question' => 'Vem har dyrast klÃ¤der?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1401101272'),
            array('QuestionID' => '259','Slug' => 'skulle-do-forst-pa-en-ode-o','Question' => 'Vem skulle dÃ¶ fÃ¶rst pÃ¥ en Ã¶de Ã¶? ','IsActive' => '1','IsDirty' => '0','DateAdded' => '1401101286'),
            array('QuestionID' => '260','Slug' => 'skulle-klara-sig-langst-i-the-hunger-games','Question' => 'Vem skulle klara sig lÃ¤ngst i the hunger games?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1401101310'),
            array('QuestionID' => '261','Slug' => 'skulle-haffa-en-ful-person-bara-for-att-fa-ligga','Question' => 'Vem skulle haffa en ful person bara fÃ¶r att fÃ¥ ligga?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1401101342'),
            array('QuestionID' => '262','Slug' => 'trogast,-mest-blond','Question' => 'Vem Ã¤r trÃ¶gast, mest blond? ','IsActive' => '0','IsDirty' => '0','DateAdded' => '1401101366'),
            array('QuestionID' => '263','Slug' => 'ser-ut-som-en-gris','Question' => 'Vem ser ut som en gris? ','IsActive' => '0','IsDirty' => '0','DateAdded' => '1401101395'),
            array('QuestionID' => '264','Slug' => 'mest-swag','Question' => 'Vem har mest SWAG? ','IsActive' => '1','IsDirty' => '0','DateAdded' => '1401101452'),
            array('QuestionID' => '265','Slug' => 'ven--bli-gay','Question' => 'Ven kommer bli gay?  ','IsActive' => '0','IsDirty' => '0','DateAdded' => '1401101465'),
            array('QuestionID' => '266','Slug' => 'ven-kissar-i-poolen','Question' => 'Ven kissar i poolen? ','IsActive' => '0','IsDirty' => '0','DateAdded' => '1401101482'),
            array('QuestionID' => '267','Slug' => 'mest-krasen','Question' => 'Vem Ã¤r mest krÃ¤sen? ','IsActive' => '1','IsDirty' => '0','DateAdded' => '1401101498'),
            array('QuestionID' => '268','Slug' => 'ljuger-pa-jag--aldrig','Question' => 'Vem ljuger pÃ¥ jag har aldrig? ','IsActive' => '1','IsDirty' => '0','DateAdded' => '1401101515'),
            array('QuestionID' => '269','Slug' => 'speglar-sig-i-varje-spegel-den-ser','Question' => 'Vem speglar sig i varje spegel den ser? ','IsActive' => '1','IsDirty' => '0','DateAdded' => '1401101531'),
            array('QuestionID' => '270','Slug' => 'skilja-sig-tre-ganger','Question' => 'Vem kommer skilja sig tre gÃ¥nger? ','IsActive' => '0','IsDirty' => '0','DateAdded' => '1401101563'),
            array('QuestionID' => '271','Slug' => 'fa-olmage','Question' => 'Vem kommer fÃ¥ Ã¶lmage? ','IsActive' => '1','IsDirty' => '0','DateAdded' => '1401101597'),
            array('QuestionID' => '272','Slug' => 'ljuger-bast','Question' => 'Vem ljuger bÃ¤st? ','IsActive' => '1','IsDirty' => '0','DateAdded' => '1401101643'),
            array('QuestionID' => '273','Slug' => 'gjort-det-roligaste-pa-fyllan','Question' => 'Vem har gjort det roligaste pÃ¥ fyllan?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1401101662'),
            array('QuestionID' => '274','Slug' => 'kollar-fortfarande-pa-bolibompa','Question' => 'Vem kollar fortfarande pÃ¥ Bolibompa? ','IsActive' => '0','IsDirty' => '0','DateAdded' => '1401101714'),
            array('QuestionID' => '275','Slug' => 'blev-av-med-oskulden-forst','Question' => 'Vem blev av med oskulden fÃ¶rst?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1401524928'),
            array('QuestionID' => '276','Slug' => 'sexigast-mamma','Question' => 'Vem har sexigast mamma?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1401524945'),
            array('QuestionID' => '277','Slug' => 'mest-vidskeplig','Question' => 'Mest vidskeplig','IsActive' => '1','IsDirty' => '0','DateAdded' => '1402689418'),
            array('QuestionID' => '278','Slug' => 'resa-mest','Question' => 'Vem kommer resa mest?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1403873342'),
            array('QuestionID' => '279','Slug' => 'resa-mest','Question' => 'Vem kommer resa mest?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1403873358'),
            array('QuestionID' => '280','Slug' => 'resa-mest','Question' => 'Vem kommer resa mest?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1403873371'),
            array('QuestionID' => '281','Slug' => 'hur-manga--du-legat-med','Question' => 'Hur mÃ¥nga har du legat med','IsActive' => '0','IsDirty' => '0','DateAdded' => '1405461051'),
            array('QuestionID' => '282','Slug' => 'mest-lik-jimmie-Ã…kesson','Question' => 'Vem Ã¤r mest lik Jimmie Ã…kesson?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1406674653'),
            array('QuestionID' => '283','Slug' => 'knappast','Question' => 'Vem Ã¤r knÃ¤ppast?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1407610291'),
            array('QuestionID' => '284','Slug' => 'legat-med-flest','Question' => 'Vem har legat med flest?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1407707114'),
            array('QuestionID' => '285','Slug' => 'hanglat-med-flest','Question' => 'Vem har hÃ¥nglat med flest? ','IsActive' => '0','IsDirty' => '0','DateAdded' => '1407707136'),
            array('QuestionID' => '286','Slug' => 'hej','Question' => 'Hej','IsActive' => '0','IsDirty' => '0','DateAdded' => '1408142589'),
            array('QuestionID' => '385','Slug' => 'far-inte-vara-din-van-javla-dumma','Question' => 'vem fÃ¥r inte vara din vÃ¤n jÃ¤vla dumma','IsActive' => '0','IsDirty' => '0','DateAdded' => '1459040555'),
            array('QuestionID' => '384','Slug' => 'far-inte-vara-din-van-javla-dumma','Question' => 'vem fÃ¥r inte vara din vÃ¤n jÃ¤vla dumma','IsActive' => '0','IsDirty' => '0','DateAdded' => '1459040555'),
            array('QuestionID' => '289','Slug' => 'langst-penis-(dags-att-matta-killar)','Question' => 'vem har lÃ¤ngst penis (Dags att mÃ¤tta killar)','IsActive' => '0','IsDirty' => '0','DateAdded' => '1413567991'),
            array('QuestionID' => '290','Slug' => 'ser-bast-ut','Question' => 'vem ser bÃ¤st ut?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1415027345'),
            array('QuestionID' => '291','Slug' => 'hade-du-helst-haft-sex-med','Question' => 'vem hade du helst haft sex med?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1415027361'),
            array('QuestionID' => '292','Slug' => 'gillar-kuk/fitta-mest','Question' => 'vem gillar kuk/fitta mest','IsActive' => '0','IsDirty' => '0','DateAdded' => '1415190453'),
            array('QuestionID' => '293','Slug' => 'fa-flest-barn','Question' => 'Vem kommer fÃ¥ flest barn? ','IsActive' => '0','IsDirty' => '0','DateAdded' => '1415386835'),
            array('QuestionID' => '294','Slug' => 'far-mest-ligg','Question' => 'Vem fÃ¥r mest ligg?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1416408115'),
            array('QuestionID' => '295','Slug' => 'bast-i-sangen','Question' => 'Vem Ã¤r bÃ¤st i sÃ¤ngen? ','IsActive' => '0','IsDirty' => '0','DateAdded' => '1417610852'),
            array('QuestionID' => '296','Slug' => 'legat-med-flest-tjejer','Question' => 'Vem har legat med flest tjejer?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1418051580'),
            array('QuestionID' => '297','Slug' => 'tycker-att-johanna--fulast-i-klassen','Question' => 'Vem tycker att Johanna Ã¤r fulast i klassen?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1418828490'),
            array('QuestionID' => '298','Slug' => 'tycker-att-johanna--fulast-i-klassen','Question' => 'Vem tycker att Johanna Ã¤r fulast i klassen?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1418828731'),
            array('QuestionID' => '299','Slug' => 'mest-sexuell','Question' => 'vem Ã¤r mest sexuell','IsActive' => '0','IsDirty' => '0','DateAdded' => '1419187999'),
            array('QuestionID' => '300','Slug' => 'av-oss-skulle-kunna-mensa-ner-sina-vita-byxor','Question' => 'Vem av oss skulle kunna mensa ner sina vita byxor?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1419188037'),
            array('QuestionID' => '301','Slug' => 'av-oss--mest-yolo','Question' => 'vem av oss Ã¤r mest YOLO','IsActive' => '0','IsDirty' => '0','DateAdded' => '1419188053'),
            array('QuestionID' => '302','Slug' => 'av-oss--mest-pengar','Question' => 'Vem av oss har mest pengar ','IsActive' => '0','IsDirty' => '0','DateAdded' => '1419628736'),
            array('QuestionID' => '303','Slug' => 'av-oss--mest-pengar','Question' => 'Vem av oss har mest pengar ','IsActive' => '0','IsDirty' => '0','DateAdded' => '1419628737'),
            array('QuestionID' => '304','Slug' => 'mest-sex','Question' => 'Vem har mest sex?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1419717194'),
            array('QuestionID' => '305','Slug' => 'bli-milf','Question' => 'Vem kommer bli milf?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1419895222'),
            array('QuestionID' => '306','Slug' => 'slampan-i-gruppen','Question' => 'Vem Ã¤r slampan i gruppen','IsActive' => '0','IsDirty' => '0','DateAdded' => '1422652913'),
            array('QuestionID' => '307','Slug' => 'som-skulle-behova-en-protes','Question' => 'Som skulle behÃ¶va en protes ','IsActive' => '0','IsDirty' => '0','DateAdded' => '1422652952'),
            array('QuestionID' => '308','Slug' => 's-ansikte--missbildat','Question' => 'vems ansikte Ã¤r missbildat','IsActive' => '0','IsDirty' => '0','DateAdded' => '1426769205'),
            array('QuestionID' => '309','Slug' => 'skulle-troligen-mest-rosta-pa-fi','Question' => 'Vem skulle troligen mest rÃ¶sta pÃ¥ FI?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1427142289'),
            array('QuestionID' => '382','Slug' => 'snuskig','Question' => 'vem Ã¤r snuskig','IsActive' => '0','IsDirty' => '0','DateAdded' => '1459040485'),
            array('QuestionID' => '383','Slug' => 'sommartid','Question' => 'vem Ã¤r sommartid','IsActive' => '0','IsDirty' => '0','DateAdded' => '1459040497'),
            array('QuestionID' => '311','Slug' => 'fgladast','Question' => 'FÃ¤rgladast','IsActive' => '0','IsDirty' => '0','DateAdded' => '1428087357'),
            array('QuestionID' => '312','Slug' => 'bast-i-sangen','Question' => 'Vem Ã¤r bÃ¤st i sÃ¤ngen?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1428184232'),
            array('QuestionID' => '313','Slug' => 'maste-fixar-sig-mest-in-for-en-...','Question' => 'Vem mÃ¥ste fixar sig mest in fÃ¶r en ...','IsActive' => '0','IsDirty' => '0','DateAdded' => '1429094014'),
            array('QuestionID' => '381','Slug' => 'aldrig-flytta-hemifran','Question' => 'vem kommer aldrig flytta hemifrÃ¥n?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1459040392'),
            array('QuestionID' => '315','Slug' => 'snyggast-familj','Question' => 'Vem har snyggast familj?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1429947977'),
            array('QuestionID' => '316','Slug' => 'strular-mest-pa-fester','Question' => 'Vem strular mest pÃ¥ fester?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1432468619'),
            array('QuestionID' => '317','Slug' => 'skulle-kunna-halla-pa-med-nagon-av-samma-kon','Question' => 'Vem skulle kunna hÃ¥lla pÃ¥ med nÃ¥gon av samma kÃ¶n?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1432468658'),
            array('QuestionID' => '318','Slug' => 'mest-pervers-pa-fyllan','Question' => 'Vem Ã¤r mest pervers pÃ¥ fyllan?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1432468731'),
            array('QuestionID' => '319','Slug' => 'skonast-pa-fyllan','Question' => 'Vem Ã¤r skÃ¶nast pÃ¥ fyllan?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1432468796'),
            array('QuestionID' => '320','Slug' => 'skulle-kunna-halla-pa-med-kompisens-bror/syster','Question' => 'Vem skulle kunna hÃ¥lla pÃ¥ med kompisens bror/syster?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1432468862'),
            array('QuestionID' => '321','Slug' => 'du-k-i-mest-i-det-h-rummet','Question' => 'Vem Ã¤r du kÃ¤r i mest i det hÃ¤r rummet?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1432468917'),
            array('QuestionID' => '322','Slug' => 'gar-alltid-all-in-pa-alla-fester','Question' => 'Vem gÃ¥r alltid all in pÃ¥ alla fester?','IsActive' => '1','IsDirty' => '0','DateAdded' => '1432468998'),
            array('QuestionID' => '323','Slug' => 'strular-mest-pa-fyllan','Question' => 'Vem strular mest pÃ¥ fyllan?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1432579265'),
            array('QuestionID' => '324','Slug' => 'hanglar-mest-pa-fester','Question' => 'Vem hÃ¥nglar mest pÃ¥ fester?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1432579288'),
            array('QuestionID' => '325','Slug' => 'vst-fotsvett','Question' => 'vem har vÃ¤rst fotsvett? ','IsActive' => '1','IsDirty' => '0','DateAdded' => '1432943813'),
            array('QuestionID' => '326','Slug' => 'bli-den-jobbigaste-pensionen','Question' => 'Vem kommer bli den jobbigaste pensionÃ¤ren?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1433885864'),
            array('QuestionID' => '327','Slug' => 'haft-sex-flest-ganger','Question' => 'Vem har haft sex flest gÃ¥nger? ','IsActive' => '0','IsDirty' => '0','DateAdded' => '1436560347'),
            array('QuestionID' => '328','Slug' => 'skulle-ha-analsex','Question' => 'Vem skulle ha analsex?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1438024128'),
            array('QuestionID' => '380','Slug' => 'sover-i-sin-mammas-kallare','Question' => 'vem sover i sin mammas kÃ¤llare?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1459040362'),
            array('QuestionID' => '330','Slug' => 'bli-full-forst','Question' => 'Vem kommer bli full fÃ¶rst','IsActive' => '0','IsDirty' => '0','DateAdded' => '1441362470'),
            array('QuestionID' => '331','Slug' => 'tog-den-i-tvaan-sist','Question' => 'Vem tog den i tvÃ¥an sist','IsActive' => '0','IsDirty' => '0','DateAdded' => '1443300502'),
            array('QuestionID' => '332','Slug' => 'snÃºes','Question' => 'snÃºes','IsActive' => '0','IsDirty' => '0','DateAdded' => '1443608522'),
            array('QuestionID' => '333','Slug' => 'hej','Question' => 'Hej','IsActive' => '0','IsDirty' => '0','DateAdded' => '1443812871'),
            array('QuestionID' => '334','Slug' => 'troligast-att-bryta-med-familjen','Question' => 'Vem Ã¤r troligast att bryta med familjen?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1444738856'),
            array('QuestionID' => '335','Slug' => 'leker-mest
','Question' => 'Vem leker mest?
','IsActive' => '0','IsDirty' => '0','DateAdded' => '1445105295'),
            array('QuestionID' => '336','Slug' => 'dusc-oftast
','Question' => 'Vem duschar oftast
','IsActive' => '1','IsDirty' => '0','DateAdded' => '1445114498'),
            array('QuestionID' => '337','Slug' => 'knullade-igor-sist','Question' => 'Vem knullade Igor sist','IsActive' => '0','IsDirty' => '0','DateAdded' => '1445341678'),
            array('QuestionID' => '377','Slug' => 'bog','Question' => 'bÃ¶g?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1459040317'),
            array('QuestionID' => '378','Slug' => 'pungkula','Question' => 'pungkula?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1459040326'),
            array('QuestionID' => '379','Slug' => 'tror-att-han-styr-ett-foretag-...','Question' => 'vem tror att han styr ett fÃ¶retag ...','IsActive' => '0','IsDirty' => '0','DateAdded' => '1459040345'),
            array('QuestionID' => '339','Slug' => 'suger-mest-kuk
','Question' => 'Vem suger mest kuk?
','IsActive' => '0','IsDirty' => '0','DateAdded' => '1445635121'),
            array('QuestionID' => '340','Slug' => 'knullar-bast-naken-i-ett-trad-pa-island','Question' => 'vem knullar bÃ¤st naken i ett trÃ¤d pÃ¥ island?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1449336275'),
            array('QuestionID' => '341','Slug' => 'holdke','Question' => 'HÃ¶ldke','IsActive' => '0','IsDirty' => '0','DateAdded' => '1451783090'),
            array('QuestionID' => '342','Slug' => 'kissa-i-en-buske','Question' => 'Kissa i en buske','IsActive' => '0','IsDirty' => '0','DateAdded' => '1451828705'),
            array('QuestionID' => '343','Slug' => 'bli-en-mordare','Question' => 'Bli en mÃ¶rdare','IsActive' => '0','IsDirty' => '0','DateAdded' => '1451828723'),
            array('QuestionID' => '344','Slug' => 'hamna-i-fangelse
','Question' => 'Hamna i fÃ¤ngelse
','IsActive' => '1','IsDirty' => '0','DateAdded' => '1451828838'),
            array('QuestionID' => '345','Slug' => 'ga-naken-pa-stan','Question' => 'GÃ¥ naken pÃ¥ stan','IsActive' => '0','IsDirty' => '0','DateAdded' => '1451828860'),
            array('QuestionID' => '346','Slug' => 'vinna-hunger-games','Question' => 'Vinna hunger games','IsActive' => '1','IsDirty' => '0','DateAdded' => '1451828874'),
            array('QuestionID' => '347','Slug' => 'bli-miljon','Question' => 'Bli miljonÃ¤r','IsActive' => '0','IsDirty' => '0','DateAdded' => '1451828886'),
            array('QuestionID' => '348','Slug' => 'bli-en-bra-kock','Question' => 'Bli en bra kock','IsActive' => '0','IsDirty' => '0','DateAdded' => '1451828895'),
            array('QuestionID' => '349','Slug' => 'glomma-nagot-viktigt','Question' => 'GlÃ¶mma nÃ¥got viktigt','IsActive' => '0','IsDirty' => '0','DateAdded' => '1451828920'),
            array('QuestionID' => '350','Slug' => 'ha-mest-f-i-skolan','Question' => 'Ha mest F i skolan','IsActive' => '1','IsDirty' => '0','DateAdded' => '1451828987'),
            array('QuestionID' => '351','Slug' => 'smartast','Question' => 'Vem Ã¤r smartast','IsActive' => '0','IsDirty' => '0','DateAdded' => '1451829002'),
            array('QuestionID' => '352','Slug' => 'skulle-bajsa-pa-en-fest','Question' => 'Vem skulle bajsa pÃ¥ en fest?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1452889184'),
            array('QuestionID' => '353','Slug' => 'skulle-bajsa-pa-en-fest','Question' => 'Vem skulle bajsa pÃ¥ en fest?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1452889189'),
            array('QuestionID' => '354','Slug' => 'skulle-spy-ner-en-bil','Question' => 'Vem skulle spy ner en bil?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1452889206'),
            array('QuestionID' => '355','Slug' => 'skulle-skaffa-en-tatuering-pa-deras-konsorgan','Question' => 'Vem skulle skaffa en tatuering pÃ¥ deras kÃ¶nsorgan?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1452889228'),
            array('QuestionID' => '356','Slug' => 'skulle-ata-moglig-mat','Question' => 'Vem skulle Ã¤ta mÃ¶glig mat?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1452889243'),
            array('QuestionID' => '376','Slug' => '99-problems-
','Question' => 'vem har 99 problems 
','IsActive' => '0','IsDirty' => '0','DateAdded' => '1459040301'),
            array('QuestionID' => '373','Slug' => 'nej','Question' => 'Nej','IsActive' => '0','IsDirty' => '0','DateAdded' => '1457464335'),
            array('QuestionID' => '374','Slug' => 'javla-dum','Question' => 'vem Ã¤r jÃ¤vla dum','IsActive' => '0','IsDirty' => '0','DateAdded' => '1459040214'),
            array('QuestionID' => '375','Slug' => 'lyssnar-mest-pa-crazyfrog','Question' => 'vem lyssnar mest pÃ¥ crazyfrog','IsActive' => '0','IsDirty' => '0','DateAdded' => '1459040277'),
            array('QuestionID' => '371','Slug' => 'svarast-att-hitta-ligg','Question' => 'Vem har svÃ¥rast att hitta ligg?','IsActive' => '1','IsDirty' => '1','DateAdded' => '1457464307'),
            array('QuestionID' => '372','Slug' => 'nej','Question' => 'Nej','IsActive' => '0','IsDirty' => '0','DateAdded' => '1457464324'),
            array('QuestionID' => '369','Slug' => 'jdjsks','Question' => 'Jdjsks','IsActive' => '0','IsDirty' => '0','DateAdded' => '1456599652'),
            array('QuestionID' => '370','Slug' => 'bajsar-pa-sig','Question' => 'Vem bajsar pÃ¥ sig','IsActive' => '0','IsDirty' => '0','DateAdded' => '1456987749'),
            array('QuestionID' => '366','Slug' => 'hhhh','Question' => 'hhhh','IsActive' => '0','IsDirty' => '0','DateAdded' => '1456516252'),
            array('QuestionID' => '367','Slug' => 'hhhh','Question' => 'hhhh','IsActive' => '0','IsDirty' => '0','DateAdded' => '1456516258'),
            array('QuestionID' => '368','Slug' => 'jdjsks','Question' => 'Jdjsks','IsActive' => '0','IsDirty' => '0','DateAdded' => '1456599645'),
            array('QuestionID' => '365','Slug' => 'yhrr2t-http://www.fylitcl7pf7kjqdduolqouaxtxbj5ing.com','Question' => 'yHrr2t http://www.FyLitCl7Pf7kjQdDUOLQOuaxTXbj5iNG.com','IsActive' => '0','IsDirty' => '0','DateAdded' => '1455119372'),
            array('QuestionID' => '364','Slug' => '3sqzql-http://www.fylitcl7pf7kjqdduolqouaxtxbj5ing.com','Question' => '3SQZQL http://www.FyLitCl7Pf7kjQdDUOLQOuaxTXbj5iNG.com','IsActive' => '0','IsDirty' => '0','DateAdded' => '1454974302'),
            array('QuestionID' => '386','Slug' => 'far-inte-vara-din-van-javla-dumma','Question' => 'vem fÃ¥r inte vara din vÃ¤n jÃ¤vla dumma','IsActive' => '0','IsDirty' => '0','DateAdded' => '1459040555'),
            array('QuestionID' => '387','Slug' => 'far-inte-vara-din-van-javla-dumma','Question' => 'vem fÃ¥r inte vara din vÃ¤n jÃ¤vla dumma','IsActive' => '0','IsDirty' => '0','DateAdded' => '1459040555'),
            array('QuestionID' => '388','Slug' => 'far-inte-vara-din-van-javla-dumma','Question' => 'vem fÃ¥r inte vara din vÃ¤n jÃ¤vla dumma','IsActive' => '0','IsDirty' => '0','DateAdded' => '1459040586'),
            array('QuestionID' => '389','Slug' => 'far-inte-vara-din-van-javla-dumma','Question' => 'vem fÃ¥r inte vara din vÃ¤n jÃ¤vla dumma','IsActive' => '0','IsDirty' => '0','DateAdded' => '1459040586'),
            array('QuestionID' => '390','Slug' => 'far-inte-vara-din-van-javla-dumma','Question' => 'vem fÃ¥r inte vara din vÃ¤n jÃ¤vla dumma','IsActive' => '0','IsDirty' => '0','DateAdded' => '1459040586'),
            array('QuestionID' => '391','Slug' => 'far-inte-vara-din-van-javla-dumma','Question' => 'vem fÃ¥r inte vara din vÃ¤n jÃ¤vla dumma','IsActive' => '0','IsDirty' => '0','DateAdded' => '1459040586'),
            array('QuestionID' => '392','Slug' => 'far-inte-vara-din-van-javla-dumma','Question' => 'vem fÃ¥r inte vara din vÃ¤n jÃ¤vla dumma','IsActive' => '0','IsDirty' => '0','DateAdded' => '1459040586'),
            array('QuestionID' => '393','Slug' => 'bli-valdtagen','Question' => 'Vem kommer bli vÃ¥ldtagen','IsActive' => '0','IsDirty' => '0','DateAdded' => '1460983617'),
            array('QuestionID' => '394','Slug' => 'onanera-mest-
','Question' => 'Vem onanera mest 
','IsActive' => '0','IsDirty' => '0','DateAdded' => '1462049178'),
            array('QuestionID' => '395','Slug' => 'en-horunge','Question' => 'Vem Ã¤r en horunge?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1463263584'),
            array('QuestionID' => '396','Slug' => 'alex--en-riktig-katgubbe','Question' => 'alex Ã¤r en riktig kÃ¥tgubbe','IsActive' => '0','IsDirty' => '0','DateAdded' => '1464337977'),
            array('QuestionID' => '397','Slug' => 'att-fa-ligga-ikvall','Question' => 'Vem kommer att fÃ¥ ligga ikvÃ¤ll?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1464362308'),
            array('QuestionID' => '398','Slug' => 'skulle-knulla-en-baver','Question' => 'Vem skulle knulla en bÃ¤ver ','IsActive' => '0','IsDirty' => '0','DateAdded' => '1465381297'),
            array('QuestionID' => '399','Slug' => 'smetigast-i-sangen','Question' => 'vem Ã¤r smetigast i sÃ¤ngen??','IsActive' => '0','IsDirty' => '0','DateAdded' => '1465848266'),
            array('QuestionID' => '400','Slug' => 'av-oss--bli-proffs-pa-nagonting','Question' => 'Vem av oss kommer bli proffs pÃ¥ nÃ¥gonting','IsActive' => '0','IsDirty' => '0','DateAdded' => '1467041146'),
            array('QuestionID' => '401','Slug' => 'snyggast','Question' => 'Vem Ã¤r snyggast','IsActive' => '0','IsDirty' => '0','DateAdded' => '1468010072'),
            array('QuestionID' => '402','Slug' => 'ju
','Question' => 'Ju
','IsActive' => '0','IsDirty' => '0','DateAdded' => '1469218416'),
            array('QuestionID' => '405','Slug' => 'snyggast-rov','Question' => 'Vem har snyggast rÃ¶v','IsActive' => '0','IsDirty' => '0','DateAdded' => '1472496171'),
            array('QuestionID' => '406','Slug' => 'snyggast-rov','Question' => 'Vem har snyggast rÃ¶v','IsActive' => '0','IsDirty' => '0','DateAdded' => '1472496176'),
            array('QuestionID' => '404','Slug' => 'vewm--bast','Question' => 'vewm Ã¤r bÃ¤st','IsActive' => '0','IsDirty' => '0','DateAdded' => '1471633042'),
            array('QuestionID' => '407','Slug' => 'fulast','Question' => 'Vem Ã¤r fulast?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1473442454'),
            array('QuestionID' => '408','Slug' => 'flest-likes-pa-sin-profilbild-(facebook)','Question' => 'Vem har flest likes pÃ¥ sin profilbild (Facebook)?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1473691119'),
            array('QuestionID' => '409','Slug' => 'storsta-drinkludret','Question' => 'StÃ¶rsta drinkludret?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1473691157'),
            array('QuestionID' => '410','Slug' => 'ok','Question' => 'Ok','IsActive' => '0','IsDirty' => '0','DateAdded' => '1474145723'),
            array('QuestionID' => '411','Slug' => 'ok','Question' => 'Ok','IsActive' => '0','IsDirty' => '0','DateAdded' => '1474145730'),
            array('QuestionID' => '412','Slug' => 'ok','Question' => 'Ok','IsActive' => '0','IsDirty' => '0','DateAdded' => '1474145739'),
            array('QuestionID' => '413','Slug' => 'uqhaha','Question' => 'Uqhaha','IsActive' => '0','IsDirty' => '0','DateAdded' => '1474411943'),
            array('QuestionID' => '414','Slug' => 'gillar-fingrar-i-rumpan-mest
','Question' => 'vem gillar fingrar i rumpan mest?
','IsActive' => '0','IsDirty' => '0','DateAdded' => '1474752349'),
            array('QuestionID' => '415','Slug' => 'spelar-mest-fickpingis','Question' => 'Vem spelar mest fickpingis?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1475371514'),
            array('QuestionID' => '416','Slug' => 'knullar-mest','Question' => 'vem knullar mest','IsActive' => '0','IsDirty' => '0','DateAdded' => '1476185487'),
            array('QuestionID' => '417','Slug' => 'bast-pa-att-dansa','Question' => 'Vem Ã¤r bÃ¤st pÃ¥ att dansa','IsActive' => '0','IsDirty' => '0','DateAdded' => '1477783510'),
            array('QuestionID' => '418','Slug' => 'mest-klantig','Question' => 'Vem Ã¤r mest klantig','IsActive' => '0','IsDirty' => '0','DateAdded' => '1478346978'),
            array('QuestionID' => '419','Slug' => 'storsta-bajkorvarna','Question' => 'StÃ¶rsta bajkorvarna','IsActive' => '0','IsDirty' => '0','DateAdded' => '1478893100'),
            array('QuestionID' => '420','Slug' => 'snyggast-hander','Question' => 'Vem har snyggast hÃ¤nder ','IsActive' => '0','IsDirty' => '0','DateAdded' => '1478987570'),
            array('QuestionID' => '421','Slug' => 'ha-dyrast-barn.','Question' => 'Vem kommer ha dyrast barn.','IsActive' => '0','IsDirty' => '0','DateAdded' => '1480796796'),
            array('QuestionID' => '422','Slug' => 'salja-sitt-barn-for-att-det--jobbigt','Question' => 'vem kommer sÃ¤lja sitt barn fÃ¶r att det Ã¤r jobbigt','IsActive' => '0','IsDirty' => '0','DateAdded' => '1480796841'),
            array('QuestionID' => '423','Slug' => 'mest-krasen','Question' => 'Vem Ã¤r mest krÃ¤sen?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1481651987'),
            array('QuestionID' => '424','Slug' => 'mest-ratchet','Question' => 'Vem Ã¤r mest ratchet? ','IsActive' => '0','IsDirty' => '0','DateAdded' => '1482699557'),
            array('QuestionID' => '426','Slug' => 'drh5za-http://www.fylitcl7pf7ojqdduolqouaxtxbj5ing.com','Question' => 'dRH5za http://www.FyLitCl7Pf7ojQdDUOLQOuaxTXbj5iNG.com','IsActive' => '0','IsDirty' => '0','DateAdded' => '1483761065'),
            array('QuestionID' => '427','Slug' => 'bdjd','Question' => 'Bdjd','IsActive' => '0','IsDirty' => '0','DateAdded' => '1484352136'),
            array('QuestionID' => '428','Slug' => 'snyggast','Question' => 'Vem Ã¤r snyggast ','IsActive' => '0','IsDirty' => '0','DateAdded' => '1484836809'),
            array('QuestionID' => '429','Slug' => 'fetast-kuuuuuuuuk-bre','Question' => 'Vem har fetast kuuuuuuuuk bre','IsActive' => '0','IsDirty' => '0','DateAdded' => '1485555786'),
            array('QuestionID' => '430','Slug' => 'ater-mest-sundays-pa-donken
','Question' => 'Vem Ã¤ter mest sundays pÃ¥ donken?
','IsActive' => '0','IsDirty' => '0','DateAdded' => '1489160341'),
            array('QuestionID' => '431','Slug' => 'skulle-du-kunna-ligga-med-i-leken','Question' => 'Vem skulle du kunna ligga med i leken?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1489424805'),
            array('QuestionID' => '432','Slug' => 'finast-i-leken','Question' => 'vem Ã¤r finast i leken?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1489424949'),
            array('QuestionID' => '433','Slug' => 'peka-pa-den-du-skulle-vilja-strula-med!','Question' => 'Peka pÃ¥ den du skulle vilja strula med!','IsActive' => '0','IsDirty' => '0','DateAdded' => '1489424998'),
            array('QuestionID' => '434','Slug' => 'peka-pa-en-dvg!','Question' => 'peka pÃ¥ en dvÃ¤rg!','IsActive' => '0','IsDirty' => '0','DateAdded' => '1489425020'),
            array('QuestionID' => '435','Slug' => 'skulle-du--vilja-ga-ner-pa','Question' => 'Vem skulle du  vilja gÃ¥ ner pÃ¥?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1489425078'),
            array('QuestionID' => '436','Slug' => '10-av-10','Question' => 'Vem Ã¤r 10 av 10?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1489425164'),
            array('QuestionID' => '437','Slug' => 'finast-leende
','Question' => 'finast leende?
','IsActive' => '0','IsDirty' => '0','DateAdded' => '1489425238'),
            array('QuestionID' => '438','Slug' => 'finast-skor','Question' => 'finast skor?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1489425245'),
            array('QuestionID' => '439','Slug' => 'finast-underklader','Question' => 'finast underklÃ¤der?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1489425255'),
            array('QuestionID' => '440','Slug' => 'finast-kropp','Question' => 'finast kropp?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1489425265'),
            array('QuestionID' => '441','Slug' => 'peka-pa-den-som--finast-rumpa
','Question' => 'peka pÃ¥ den som har finast rumpa?
','IsActive' => '0','IsDirty' => '0','DateAdded' => '1489425295'),
            array('QuestionID' => '442','Slug' => 'svarast-att-fa','Question' => 'vem Ã¤r svÃ¥rast att fÃ¥?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1489425694'),
            array('QuestionID' => '443','Slug' => 'skulle-du-kunna-tanka-dig-att-ha-en-relation-med','Question' => 'vem skulle du kunna tÃ¤nka dig att ha en relation med?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1489425742'),
            array('QuestionID' => '444','Slug' => 'troligast-haft-sex-med-nagon-av-samma-kon','Question' => 'Vem har troligast haft sex med nÃ¥gon av samma kÃ¶n?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1491239314'),
            array('QuestionID' => '445','Slug' => 'troligast-haft-sex-med-nagon-av-samma-kon','Question' => 'Vem har troligast haft sex med nÃ¥gon av samma kÃ¶n?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1491239319'),
            array('QuestionID' => '446','Slug' => 'skulle-rana-hemlos','Question' => 'Vem skulle rÃ¥na hemlÃ¶s?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1491596072'),
            array('QuestionID' => '447','Slug' => 'blaskka','Question' => 'Blaskka','IsActive' => '0','IsDirty' => '0','DateAdded' => '1492197976'),
            array('QuestionID' => '448','Slug' => 'snyggast-kropp','Question' => 'Vem har snyggast kropp?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1493619643'),
            array('QuestionID' => '449','Slug' => 'snyggast-kropp','Question' => 'Vem har snyggast kropp?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1493619651'),
            array('QuestionID' => '450','Slug' => 'suger-mest-kuk','Question' => 'Vem suger mest kuk','IsActive' => '0','IsDirty' => '0','DateAdded' => '1494078074'),
            array('QuestionID' => '451','Slug' => 'who&#039;s-the-most-likely-to-break-up-a-marriage','Question' => 'Who&#039;s the most likely to break up a marriage? ','IsActive' => '0','IsDirty' => '0','DateAdded' => '1495315789'),
            array('QuestionID' => '452','Slug' => 'foghorn--the','Question' => 'Foghorn ? The ','IsActive' => '0','IsDirty' => '0','DateAdded' => '1495315815'),
            array('QuestionID' => '453','Slug' => 'the-we','Question' => 'The? We ','IsActive' => '0','IsDirty' => '0','DateAdded' => '1495315824'),
            array('QuestionID' => '454','Slug' => 'rhythm-of-the-year-0','Question' => 'Rhythm of the year ?0','IsActive' => '0','IsDirty' => '0','DateAdded' => '1495315844'),
            array('QuestionID' => '455','Slug' => 'chjoo','Question' => 'Chjoo','IsActive' => '0','IsDirty' => '0','DateAdded' => '1495315848'),
            array('QuestionID' => '456','Slug' => 'gghji','Question' => 'Gghji','IsActive' => '0','IsDirty' => '0','DateAdded' => '1495315856'),
            array('QuestionID' => '457','Slug' => 'ffjko','Question' => 'Ffjko','IsActive' => '0','IsDirty' => '0','DateAdded' => '1495315863'),
            array('QuestionID' => '458','Slug' => 'who-gets-the-must-drunk-easiest','Question' => 'Who gets the must drunk easiest?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1495315916'),
            array('QuestionID' => '459','Slug' => 'the-person-with-the-most-of-the-drink-left-has-to-drink','Question' => 'The person with the most of the drink left has to drink','IsActive' => '0','IsDirty' => '0','DateAdded' => '1495315966'),
            array('QuestionID' => '460','Slug' => 'aldrig-haft-sex','Question' => 'Vem har aldrig haft sex?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1495316000'),
            array('QuestionID' => '461','Slug' => 'legat-med-flest-
','Question' => 'Vem har legat med flest 
','IsActive' => '0','IsDirty' => '0','DateAdded' => '1495920716'),
            array('QuestionID' => '462','Slug' => 'legat-med-flest-
','Question' => 'Vem har legat med flest 
','IsActive' => '0','IsDirty' => '0','DateAdded' => '1495920734'),
            array('QuestionID' => '463','Slug' => 'minst-har-pa-kanet','Question' => 'Vem har minst hÃ¥r pÃ¥ kÃ¤net','IsActive' => '0','IsDirty' => '0','DateAdded' => '1497038465'),
            array('QuestionID' => '464','Slug' => 'dummast','Question' => 'Vem Ã¤r dummast?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1497127746'),
            array('QuestionID' => '465','Slug' => 'dummast','Question' => 'Vem Ã¤r dummast?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1497127754'),
            array('QuestionID' => '466','Slug' => 'haft-flest-forhallande','Question' => 'Vem har haft flest fÃ¶rhÃ¥llande ','IsActive' => '0','IsDirty' => '0','DateAdded' => '1497290167'),
            array('QuestionID' => '467','Slug' => 'fiskar-mest','Question' => 'Vem fiskar mest?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1498244635'),
            array('QuestionID' => '468','Slug' => 'knullar-bast','Question' => 'knullar bÃ¤st?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1498934972'),
            array('QuestionID' => '469','Slug' => 'hetast-i-rummet','Question' => 'Vem Ã¤r hetast i rummet?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1499989979'),
            array('QuestionID' => '470','Slug' => 'hetast-i-rummet','Question' => 'Vem Ã¤r hetast i rummet?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1499989986'),
            array('QuestionID' => '471','Slug' => 'ha-haft-mest-sex','Question' => 'Vem ha haft mest sex','IsActive' => '0','IsDirty' => '0','DateAdded' => '1500804091'),
            array('QuestionID' => '472','Slug' => 'hej','Question' => 'Hej','IsActive' => '0','IsDirty' => '0','DateAdded' => '1501798549'),
            array('QuestionID' => '473','Slug' => 'hej','Question' => 'Hej','IsActive' => '0','IsDirty' => '0','DateAdded' => '1501955138'),
            array('QuestionID' => '474','Slug' => 'gillar-lisa-bast','Question' => 'Vem gillar Lisa bÃ¤st','IsActive' => '0','IsDirty' => '0','DateAdded' => '1504892379'),
            array('QuestionID' => '475','Slug' => 'mest-sex
','Question' => 'vem har mest sex
','IsActive' => '0','IsDirty' => '0','DateAdded' => '1506113156'),
            array('QuestionID' => '476','Slug' => 'string-offtast','Question' => 'vem har string offtast ','IsActive' => '0','IsDirty' => '0','DateAdded' => '1506113177'),
            array('QuestionID' => '477','Slug' => 'skulle-kunna-ha-sex-pa-stranden-bland-massa-folk
','Question' => 'Vem skulle kunna ha sex pÃ¥ stranden bland massa folk?
','IsActive' => '0','IsDirty' => '0','DateAdded' => '1506113231'),
            array('QuestionID' => '478','Slug' => 'stonar-hokst-
','Question' => 'vem stÃ¶nar hÃ¶kst 
','IsActive' => '0','IsDirty' => '0','DateAdded' => '1506113250'),
            array('QuestionID' => '479','Slug' => 'skiter-mast','Question' => 'vem skiter mÃ¤st','IsActive' => '0','IsDirty' => '0','DateAdded' => '1506113275'),
            array('QuestionID' => '480','Slug' => 'storst-brost','Question' => 'vem har stÃ¶rst brÃ¶st','IsActive' => '0','IsDirty' => '0','DateAdded' => '1506113293'),
            array('QuestionID' => '481','Slug' => 'skulle-kunna-ha-sex-n-foraldrarna-sitter-i-rummet-utanfor-och-kollar-pa-tv','Question' => 'vem skulle kunna ha sex nÃ¤r fÃ¶rÃ¤ldrarna sitter i rummet utanfÃ¶r och kollar pÃ¥ tv?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1506113328'),
            array('QuestionID' => '482','Slug' => 'ven-gillar-kuk','Question' => 'Ven gillar kuk','IsActive' => '0','IsDirty' => '0','DateAdded' => '1506709647'),
            array('QuestionID' => '483','Slug' => 'tycker-att-personen-sjalv--cool','Question' => 'Vem tycker att personen sjÃ¤lv Ã¤r cool?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1506803314'),
            array('QuestionID' => '484','Slug' => 'bast-slack','Question' => 'Vem har bÃ¤st slÃ¤ck','IsActive' => '0','IsDirty' => '0','DateAdded' => '1509310659'),
            array('QuestionID' => '485','Slug' => 'kullar-mest-med-sin-mamma
','Question' => 'Vem har kullar mest med sin mamma
','IsActive' => '0','IsDirty' => '0','DateAdded' => '1510141922'),
            array('QuestionID' => '486','Slug' => 'flortar-med-andra-pa-badoo/tinder','Question' => 'Vem flÃ¶rtar med andra pÃ¥ badoo/tinder?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1511211980'),
            array('QuestionID' => '487','Slug' => 'flortar-med-andra-pa-sin-badoo/tinder','Question' => 'Vem flÃ¶rtar med andra pÃ¥ sin badoo/tinder ','IsActive' => '0','IsDirty' => '0','DateAdded' => '1511212058'),
            array('QuestionID' => '488','Slug' => 'ha-sex-oftast-
','Question' => 'Vem kommer ha sex oftast 
','IsActive' => '0','IsDirty' => '0','DateAdded' => '1511333493'),
            array('QuestionID' => '489','Slug' => 'luktar-mest-bajs','Question' => 'Vem luktar mest bajs ','IsActive' => '0','IsDirty' => '0','DateAdded' => '1511642232'),
            array('QuestionID' => '490','Slug' => 'knullar-mest
','Question' => 'Vem Knullar mest
','IsActive' => '0','IsDirty' => '0','DateAdded' => '1511802847'),
            array('QuestionID' => '491','Slug' => 'fulast-utan-smink','Question' => 'Vem Ã¤r fulast utan smink?','IsActive' => '0','IsDirty' => '0','DateAdded' => '1512163979'),
            array('QuestionID' => '492','Slug' => 'jsjdjd','Question' => 'Jsjdjd','IsActive' => '0','IsDirty' => '0','DateAdded' => '1513154648'),
            array('QuestionID' => '493','Slug' => 'ha-mest-pengar-n-den--stor
','Question' => 'Vem kommer ha mest pengar nÃ¤r den Ã¤r stor???
','IsActive' => '0','IsDirty' => '0','DateAdded' => '1513282337'),
            array('QuestionID' => '494','Slug' => 'en-doda-en-sova-med-en-gifta-dej-med-

channing-tatum-justin-bieber--chris-brown','Question' => 'En dÃ¶da en sova med en gifta dej med 

Channing tatum Justin Bieber  Chris Brown ','IsActive' => '0','IsDirty' => '0','DateAdded' => '1513489020'),
            array('QuestionID' => '495','Slug' => 'skulle-du-radda-din-syster-eller-din-fru-man','Question' => 'Vem skulle du rÃ¤dda din syster eller din fru man ','IsActive' => '0','IsDirty' => '0','DateAdded' => '1513489051')
        );


        foreach($Questions as $q) {

            $replace = ['Ã¤', 'Ã¶', 'Ã¥'];
            $with = ['ä', 'ö', 'å'];

            $sorted[] = [
                'id' => $q['QuestionID'],
                'slug' => $q['Slug'],
                'question' => str_replace($replace, $with, $q['Question']),
                'isActive' => $q['IsActive'],
                'isDirty' => $q['IsDirty'],
                'created_at' => $q['DateAdded'] > 0 ? date('Y-m-d H:i:s', $q['DateAdded']) : null,
            ];

        }


        foreach($sorted as $s) {
            \App\Models\Question::insert($s);
        }



    }
}
